import { useState, useCallback } from "react";
import { Loader2, CheckCircle, XCircle, ShieldCheck, Maximize2, FileCode, Bot, UserCheck } from "lucide-react";
import { motion } from "framer-motion";
import type { BatchProgress, Diff, RunStatus, VerifyResult } from "../types";
import { getApiUrl } from "../api";
import { cn } from "../lib/cn";
import { ScreenshotLightbox } from "./ScreenshotLightbox";

interface Props {
  diff: Diff | null;
  status: RunStatus;
  runId: string | null;
  onApprove: () => void;
  verifyResult: VerifyResult | null;
  batchProgress: BatchProgress | null;
}

export function DiffPanel({ diff, status, runId, onApprove, verifyResult, batchProgress }: Props) {
  const [lightboxSrc, setLightboxSrc] = useState<string | null>(null);
  const [lightboxAlt, setLightboxAlt] = useState("");
  const openScreenshot = useCallback((src: string, alt: string) => {
    setLightboxSrc(src);
    setLightboxAlt(alt);
  }, []);
  const closeLightbox = useCallback(() => setLightboxSrc(null), []);

  if (!diff) {
    if (status === "awaiting_approval") {
      return (
        <div className="flex flex-col items-center justify-center h-full gap-4 p-6">
          <div className="w-14 h-14 rounded-full bg-orange-500/10 border border-orange-500/30 flex items-center justify-center">
            <UserCheck className="w-6 h-6 text-orange-400" aria-hidden="true" />
          </div>
          <p className="text-gray-400 text-sm text-center">
            Review the fixes in the Findings panel, or approve all to continue the pipeline.
          </p>
          <button
            onClick={onApprove}
            className={cn(
              "flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold transition-all",
              "text-emerald-400 border border-emerald-500/30 hover:bg-emerald-500/10 hover:border-emerald-500/50"
            )}
          >
            <ShieldCheck className="w-4 h-4" aria-hidden="true" />
            Approve & Continue
          </button>
        </div>
      );
    }
    const isIdle = status === "idle" || status === "complete" || status === "failed";
    return (
      <div className="flex flex-col items-center justify-center h-full text-gray-500 text-sm p-6 gap-4">
        {isIdle ? (
          <>
            <div className="w-14 h-14 rounded-full bg-nova-500/10 border border-nova-500/20 flex items-center justify-center">
              <FileCode className="w-6 h-6 text-nova-400/60" aria-hidden="true" />
            </div>
            <div className="text-center space-y-2 max-w-xs">
              <p className="text-gray-400 font-medium">How NovaGuard Works</p>
              <div className="text-xs text-gray-600 space-y-1.5">
                <p><strong className="text-blue-400/80">1.</strong> Nova Act crawls your page via real Chromium</p>
                <p><strong className="text-purple-400/80">2.</strong> Nova 2 Lite analyzes screenshots + DOM for WCAG 2.2 issues</p>
                <p><strong className="text-amber-400/80">3.</strong> Nova 2 Lite generates minimal HTML patches</p>
                <p><strong className="text-orange-400/80">4.</strong> You review and approve (human-in-the-loop)</p>
                <p><strong className="text-indigo-400/80">5.</strong> Nova Act applies fixes via browser automation</p>
                <p><strong className="text-cyan-400/80">6.</strong> Nova Act verifies fixes with before/after proof</p>
              </div>
            </div>
          </>
        ) : (
          <>
            <FileCode className="w-8 h-8 text-gray-600" aria-hidden="true" />
            <p className="text-center">
              Click <strong className="text-gray-400">Review Fix</strong> on a finding to inspect the generated patch.
              <br />
              <span className="text-gray-600 text-xs">Nova 2 Lite generates minimal HTML diffs with WCAG rationale.</span>
            </p>
          </>
        )}
      </div>
    );
  }

  const screenshotBase = runId ? `${getApiUrl()}/runs/${runId}/screenshots` : "";
  const beforeScreenshot = runId ? `${screenshotBase}/page_load.png` : null;
  const afterScreenshot =
    runId && diff.after_screenshot ? `${screenshotBase}/${diff.after_screenshot}` : null;

  return (
    <div className="flex flex-col gap-5 p-5 overflow-y-auto">
      {/* Header with model badge */}
      <div className="flex items-center gap-3">
        <h3 className="text-sm font-semibold text-gray-300 uppercase tracking-wider">
          Fix Diff &mdash; Finding {diff.finding_id}
        </h3>
        <span className="inline-flex items-center gap-1 px-2 py-0.5 rounded text-[9px] font-semibold border text-purple-400 bg-purple-500/10 border-purple-500/20">
          <Bot className="w-2.5 h-2.5" aria-hidden="true" />
          Generated by Nova 2 Lite
        </span>
      </div>

      {/* HTML Before / After */}
      <div className="grid grid-cols-2 gap-3">
        <div>
          <p className="text-xs font-semibold text-red-400 mb-1.5 uppercase tracking-wide">Before</p>
          <pre
            className="text-xs bg-red-500/5 border border-red-500/20 rounded-lg p-3 whitespace-pre-wrap break-all text-gray-300 leading-relaxed font-mono"
            aria-label="HTML before fix"
          >
            {diff.before_html}
          </pre>
        </div>
        <div>
          <p className="text-xs font-semibold text-emerald-400 mb-1.5 uppercase tracking-wide">After</p>
          <pre
            className="text-xs bg-emerald-500/5 border border-emerald-500/20 rounded-lg p-3 whitespace-pre-wrap break-all text-gray-300 leading-relaxed font-mono"
            aria-label="HTML after fix"
          >
            {diff.after_html}
          </pre>
        </div>
      </div>

      {/* Patch */}
      {diff.patch && (
        <div>
          <p className="text-xs font-semibold text-gray-500 mb-1.5 uppercase tracking-wide">Unified Diff</p>
          <pre className="text-xs bg-gray-950 text-emerald-400 rounded-lg p-3 overflow-x-auto whitespace-pre leading-relaxed border border-surface-border font-mono">
            {diff.patch}
          </pre>
        </div>
      )}

      {/* Rationale */}
      <div className="glass rounded-lg p-4 border-nova-500/20">
        <p className="text-xs font-semibold text-nova-300 mb-1 uppercase tracking-wide">Rationale</p>
        <p className="text-sm text-gray-300 leading-relaxed">{diff.rationale}</p>
      </div>

      {/* Approve button with human-in-the-loop badge */}
      {status === "awaiting_approval" && (
        <div className="flex items-center gap-3">
          <motion.button
            whileHover={{ scale: 1.02 }}
            whileTap={{ scale: 0.98 }}
            onClick={onApprove}
            className={cn(
              "flex items-center gap-2 px-6 py-2.5 rounded-lg font-semibold transition-all",
              "text-emerald-400 border border-emerald-500/30 hover:bg-emerald-500/10 hover:border-emerald-500/50"
            )}
          >
            <ShieldCheck className="w-4 h-4" aria-hidden="true" />
            Approve & Apply Fix
          </motion.button>
          <span className="flex items-center gap-1 text-[10px] text-orange-400 font-medium">
            <UserCheck className="w-3.5 h-3.5" aria-hidden="true" />
            Human approval required
          </span>
        </div>
      )}

      {/* In-progress */}
      {(status === "applying" || status === "verifying") && (
        <div className="flex items-center gap-2.5 text-sm text-gray-400" role="status" aria-live="polite">
          <Loader2 className="w-5 h-5 animate-spin text-nova-400" aria-hidden="true" />
          {batchProgress && batchProgress.total > 1
            ? `${batchProgress.stage === "apply" ? "Applying" : "Verifying"} fix ${batchProgress.current} of ${batchProgress.total}...`
            : status === "applying" ? "Nova Act is applying fix via browser automation..." : "Nova Act is verifying the fix..."}
        </div>
      )}

      {/* Before / After screenshots */}
      {(afterScreenshot || verifyResult) && beforeScreenshot && (
        <div>
          <p className="text-xs font-semibold text-gray-500 mb-2 uppercase tracking-wide">
            Before / After Visual Proof
          </p>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <p className="text-xs text-red-400 font-medium mb-1">Before</p>
              <button
                onClick={() => openScreenshot(beforeScreenshot, "Page before accessibility fix")}
                className="relative group w-full rounded-lg overflow-hidden border border-surface-border hover:border-red-500/40 transition-colors cursor-pointer"
                aria-label="View full before screenshot"
              >
                <img
                  src={beforeScreenshot}
                  alt="Screenshot of page before accessibility fix was applied"
                  className="w-full rounded-lg shadow-md"
                />
                <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 flex items-center justify-center transition-colors">
                  <Maximize2 className="w-5 h-5 text-white opacity-0 group-hover:opacity-100 transition-opacity" />
                </div>
              </button>
            </div>
            <div>
              <p className="text-xs text-emerald-400 font-medium mb-1">After</p>
              {afterScreenshot ? (
                <button
                  onClick={() => openScreenshot(afterScreenshot, "Page after accessibility fix")}
                  className="relative group w-full rounded-lg overflow-hidden border border-surface-border hover:border-emerald-500/40 transition-colors cursor-pointer"
                  aria-label="View full after screenshot"
                >
                  <img
                    src={afterScreenshot}
                    alt="Screenshot of page after accessibility fix was applied"
                    className="w-full rounded-lg shadow-md"
                  />
                  <div className="absolute inset-0 bg-black/0 group-hover:bg-black/40 flex items-center justify-center transition-colors">
                    <Maximize2 className="w-5 h-5 text-white opacity-0 group-hover:opacity-100 transition-opacity" />
                  </div>
                </button>
              ) : (
                <div className="w-full h-32 rounded-lg border border-surface-border bg-surface-raised flex items-center justify-center text-xs text-gray-500">
                  Waiting for screenshot...
                </div>
              )}
            </div>
          </div>
        </div>
      )}

      {/* Verify result */}
      {verifyResult && (
        <motion.div
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          className={cn(
            "rounded-lg p-4 border flex items-start gap-3",
            verifyResult.passed
              ? "bg-emerald-500/10 border-emerald-500/30"
              : "bg-red-500/10 border-red-500/30"
          )}
          role="alert"
        >
          {verifyResult.passed ? (
            <CheckCircle className="w-5 h-5 text-emerald-400 flex-shrink-0 mt-0.5" aria-hidden="true" />
          ) : (
            <XCircle className="w-5 h-5 text-red-400 flex-shrink-0 mt-0.5" aria-hidden="true" />
          )}
          <div>
            <p className={cn("font-semibold text-sm", verifyResult.passed ? "text-emerald-300" : "text-red-300")}>
              {verifyResult.passed ? "Verification Passed" : "Verification Failed"}
            </p>
            <p className="text-xs text-gray-400 mt-0.5">{verifyResult.details}</p>
          </div>
        </motion.div>
      )}

      <ScreenshotLightbox src={lightboxSrc} alt={lightboxAlt} onClose={closeLightbox} />
    </div>
  );
}
